language: node_js
node_js:
  - stable
before_install:
  sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
install:
  - yarn install
script:
  - yarn coverage
after_script: "cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
